name: Thanks PR

on: [pull_request]

jobs:
  punny:
    runs-on: ubuntu-latest
    name: Reward PRs with a random pun
    steps:
    - uses: AlexLakatos/puns-dev-action@v1.2
      id: pun
    - uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message: |
          ${{ steps.pun.outputs.pun }}
          ${{ steps.pun.outputs.punchline }}
