name: Thanks PR

on: [pull_request]

jobs:
  punny:
    runs-on: ubuntu-latest
    name: Reward PRs with a random pun
    steps:
    - uses: AlexLakatos/puns-dev-action@v1.2
      id: pun
    - uses: allthatjazzleo/actions-pull-request-add-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          ${{ steps.pun.outputs.pun }}
          ${{ steps.pun.outputs.punchline }}
